version: '3'

services:
  api_backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      - PSQL_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/enrolment_java_db
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enrolment_java_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "enrolment_java_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"